// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=.js"
// @generated from file doge.proto (package fractalengine.rpc.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file doge.proto.
 */
export const file_doge: GenFile = /*@__PURE__*/
  fileDesc("Cgpkb2dlLnByb3RvEhRmcmFjdGFsZW5naW5lLnJwYy52MSJUChBEb2dlVG9wVXBSZXF1ZXN0EkAKB2FkZHJlc3MYASABKAlCL7pILHIqMiheKD86W0RBbW4yXSlbMS05QS1ISi1OUC1aYS1rbS16XXsyNSwzNH0kIiIKEURvZ2VUb3BVcFJlc3BvbnNlEg0KBXZhbHVlGAEgASgJIhQKEkRvZ2VDb25maXJtUmVxdWVzdCKLAQoTRG9nZUNvbmZpcm1SZXNwb25zZRJFCgZ2YWx1ZXMYASADKAsyNS5mcmFjdGFsZW5naW5lLnJwYy52MS5Eb2dlQ29uZmlybVJlc3BvbnNlLlZhbHVlc0VudHJ5Gi0KC1ZhbHVlc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiMgoPRG9nZVNlbmRSZXF1ZXN0Eh8KF2VuY29kZWRfdHJhbnNhY3Rpb25faGV4GAEgASgJIioKEERvZ2VTZW5kUmVzcG9uc2USFgoOdHJhbnNhY3Rpb25faWQYASABKAlCLlosZG9nZWNvaW4ub3JnL2ZyYWN0YWwtZW5naW5lL3BrZy9ycGMvcHJvdG9jb2xiBnByb3RvMw", [file_buf_validate_validate]);

/**
 * @generated from message fractalengine.rpc.v1.DogeTopUpRequest
 */
export type DogeTopUpRequest = Message<"fractalengine.rpc.v1.DogeTopUpRequest"> & {
  /**
   * @generated from field: string address = 1;
   */
  address: string;
};

/**
 * Describes the message fractalengine.rpc.v1.DogeTopUpRequest.
 * Use `create(DogeTopUpRequestSchema)` to create a new message.
 */
export const DogeTopUpRequestSchema: GenMessage<DogeTopUpRequest> = /*@__PURE__*/
  messageDesc(file_doge, 0);

/**
 * @generated from message fractalengine.rpc.v1.DogeTopUpResponse
 */
export type DogeTopUpResponse = Message<"fractalengine.rpc.v1.DogeTopUpResponse"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message fractalengine.rpc.v1.DogeTopUpResponse.
 * Use `create(DogeTopUpResponseSchema)` to create a new message.
 */
export const DogeTopUpResponseSchema: GenMessage<DogeTopUpResponse> = /*@__PURE__*/
  messageDesc(file_doge, 1);

/**
 * @generated from message fractalengine.rpc.v1.DogeConfirmRequest
 */
export type DogeConfirmRequest = Message<"fractalengine.rpc.v1.DogeConfirmRequest"> & {
};

/**
 * Describes the message fractalengine.rpc.v1.DogeConfirmRequest.
 * Use `create(DogeConfirmRequestSchema)` to create a new message.
 */
export const DogeConfirmRequestSchema: GenMessage<DogeConfirmRequest> = /*@__PURE__*/
  messageDesc(file_doge, 2);

/**
 * @generated from message fractalengine.rpc.v1.DogeConfirmResponse
 */
export type DogeConfirmResponse = Message<"fractalengine.rpc.v1.DogeConfirmResponse"> & {
  /**
   * @generated from field: map<string, string> values = 1;
   */
  values: { [key: string]: string };
};

/**
 * Describes the message fractalengine.rpc.v1.DogeConfirmResponse.
 * Use `create(DogeConfirmResponseSchema)` to create a new message.
 */
export const DogeConfirmResponseSchema: GenMessage<DogeConfirmResponse> = /*@__PURE__*/
  messageDesc(file_doge, 3);

/**
 * @generated from message fractalengine.rpc.v1.DogeSendRequest
 */
export type DogeSendRequest = Message<"fractalengine.rpc.v1.DogeSendRequest"> & {
  /**
   * @generated from field: string encoded_transaction_hex = 1;
   */
  encodedTransactionHex: string;
};

/**
 * Describes the message fractalengine.rpc.v1.DogeSendRequest.
 * Use `create(DogeSendRequestSchema)` to create a new message.
 */
export const DogeSendRequestSchema: GenMessage<DogeSendRequest> = /*@__PURE__*/
  messageDesc(file_doge, 4);

/**
 * @generated from message fractalengine.rpc.v1.DogeSendResponse
 */
export type DogeSendResponse = Message<"fractalengine.rpc.v1.DogeSendResponse"> & {
  /**
   * @generated from field: string transaction_id = 1;
   */
  transactionId: string;
};

/**
 * Describes the message fractalengine.rpc.v1.DogeSendResponse.
 * Use `create(DogeSendResponseSchema)` to create a new message.
 */
export const DogeSendResponseSchema: GenMessage<DogeSendResponse> = /*@__PURE__*/
  messageDesc(file_doge, 5);

