// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=.js"
// @generated from file health.proto (package fractalengine.rpc.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file health.proto.
 */
export const file_health: GenFile = /*@__PURE__*/
  fileDesc("CgxoZWFsdGgucHJvdG8SFGZyYWN0YWxlbmdpbmUucnBjLnYxIqYBChFHZXRIZWFsdGhSZXNwb25zZRINCgVjaGFpbhgBIAEoCRIcChRjdXJyZW50X2Jsb2NrX2hlaWdodBgCIAEoBRIbChNsYXRlc3RfYmxvY2tfaGVpZ2h0GAMgASgFEhIKCnVwZGF0ZWRfYXQYBCABKAkSDwoHdmVyc2lvbhgFIAEoCRIXCg93YWxsZXRzX2VuYWJsZWQYBiABKAgSCQoBaBgHIAEoCSISChBHZXRIZWFsdGhSZXF1ZXN0Qi5aLGRvZ2Vjb2luLm9yZy9mcmFjdGFsLWVuZ2luZS9wa2cvcnBjL3Byb3RvY29sYghlZGl0aW9uc3DoBw");

/**
 * @generated from message fractalengine.rpc.v1.GetHealthResponse
 */
export type GetHealthResponse = Message<"fractalengine.rpc.v1.GetHealthResponse"> & {
  /**
   * @generated from field: string chain = 1;
   */
  chain: string;

  /**
   * @generated from field: int32 current_block_height = 2;
   */
  currentBlockHeight: number;

  /**
   * @generated from field: int32 latest_block_height = 3;
   */
  latestBlockHeight: number;

  /**
   * @generated from field: string updated_at = 4;
   */
  updatedAt: string;

  /**
   * @generated from field: string version = 5;
   */
  version: string;

  /**
   * @generated from field: bool wallets_enabled = 6;
   */
  walletsEnabled: boolean;

  /**
   * @generated from field: string h = 7;
   */
  h: string;
};

/**
 * Describes the message fractalengine.rpc.v1.GetHealthResponse.
 * Use `create(GetHealthResponseSchema)` to create a new message.
 */
export const GetHealthResponseSchema: GenMessage<GetHealthResponse> = /*@__PURE__*/
  messageDesc(file_health, 0);

/**
 * @generated from message fractalengine.rpc.v1.GetHealthRequest
 */
export type GetHealthRequest = Message<"fractalengine.rpc.v1.GetHealthRequest"> & {
};

/**
 * Describes the message fractalengine.rpc.v1.GetHealthRequest.
 * Use `create(GetHealthRequestSchema)` to create a new message.
 */
export const GetHealthRequestSchema: GenMessage<GetHealthRequest> = /*@__PURE__*/
  messageDesc(file_health, 1);

