// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=.js"
// @generated from file mints.proto (package fractalengine.rpc.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb.js";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { AssetManager, Mint, SignatureRequirementType, StringInterfaceMap } from "./common_pb.js";
import { file_common } from "./common_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mints.proto.
 */
export const file_mints: GenFile = /*@__PURE__*/
  fileDesc("CgttaW50cy5wcm90bxIUZnJhY3RhbGVuZ2luZS5ycGMudjEiaAoPR2V0TWludHNSZXF1ZXN0EioKBWxpbWl0GAEgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkludDMyVmFsdWUSKQoEcGFnZRgCIAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5JbnQzMlZhbHVlIjgKDkdldE1pbnRSZXF1ZXN0EiYKBGhhc2gYASABKAlCGLpIFXITMhFeW2EtZkEtRjAtOV17NjR9JCJpChBHZXRNaW50c1Jlc3BvbnNlEg0KBWxpbWl0GAEgASgFEikKBW1pbnRzGAIgAygLMhouZnJhY3RhbGVuZ2luZS5ycGMudjEuTWludBIMCgRwYWdlGAMgASgFEg0KBXRvdGFsGAQgASgFIjsKD0dldE1pbnRSZXNwb25zZRIoCgRtaW50GAEgASgLMhouZnJhY3RhbGVuZ2luZS5ycGMudjEuTWludCJ7ChFDcmVhdGVNaW50UmVxdWVzdBI/CgdwYXlsb2FkGAEgASgLMi4uZnJhY3RhbGVuZ2luZS5ycGMudjEuQ3JlYXRlTWludFJlcXVlc3RQYXlsb2FkEhIKCnB1YmxpY19rZXkYAiABKAkSEQoJc2lnbmF0dXJlGAMgASgJItkEChhDcmVhdGVNaW50UmVxdWVzdFBheWxvYWQSOgoOYXNzZXRfbWFuYWdlcnMYASADKAsyIi5mcmFjdGFsZW5naW5lLnJwYy52MS5Bc3NldE1hbmFnZXISGAoQY29udHJhY3Rfb2Zfc2FsZRgCIAEoCRIcCgtkZXNjcmlwdGlvbhgDIAEoCUIHukgEcgIQARIQCghmZWVkX3VybBgEIAEoCRIfCg5mcmFjdGlvbl9jb3VudBgFIAEoBUIHukgEGgIgABJACg5sb2NrdXBfb3B0aW9ucxgGIAEoCzIoLmZyYWN0YWxlbmdpbmUucnBjLnYxLlN0cmluZ0ludGVyZmFjZU1hcBI6CghtZXRhZGF0YRgHIAEoCzIoLmZyYWN0YWxlbmdpbmUucnBjLnYxLlN0cmluZ0ludGVyZmFjZU1hcBIWCg5taW5fc2lnbmF0dXJlcxgIIAEoBRJGCg1vd25lcl9hZGRyZXNzGAkgASgJQi+6SCxyKjIoXig/OltEQW1uMl0pWzEtOUEtSEotTlAtWmEta20tel17MjUsMzR9JBI+CgxyZXF1aXJlbWVudHMYCiABKAsyKC5mcmFjdGFsZW5naW5lLnJwYy52MS5TdHJpbmdJbnRlcmZhY2VNYXASUgoac2lnbmF0dXJlX3JlcXVpcmVtZW50X3R5cGUYCyABKA4yLi5mcmFjdGFsZW5naW5lLnJwYy52MS5TaWduYXR1cmVSZXF1aXJlbWVudFR5cGUSDAoEdGFncxgMIAMoCRIWCgV0aXRsZRgNIAEoCUIHukgEcgIQASJeChJDcmVhdGVNaW50UmVzcG9uc2USIAoYZW5jb2RlZF90cmFuc2FjdGlvbl9ib2R5GAEgASgJEiYKBGhhc2gYAiABKAlCGLpIFXITMhFeW2EtZkEtRjAtOV17NjR9JEIuWixkb2dlY29pbi5vcmcvZnJhY3RhbC1lbmdpbmUvcGtnL3JwYy9wcm90b2NvbGIGcHJvdG8z", [file_buf_validate_validate, file_google_protobuf_wrappers, file_common]);

/**
 * @generated from message fractalengine.rpc.v1.GetMintsRequest
 */
export type GetMintsRequest = Message<"fractalengine.rpc.v1.GetMintsRequest"> & {
  /**
   * @generated from field: google.protobuf.Int32Value limit = 1;
   */
  limit?: number;

  /**
   * @generated from field: google.protobuf.Int32Value page = 2;
   */
  page?: number;
};

/**
 * Describes the message fractalengine.rpc.v1.GetMintsRequest.
 * Use `create(GetMintsRequestSchema)` to create a new message.
 */
export const GetMintsRequestSchema: GenMessage<GetMintsRequest> = /*@__PURE__*/
  messageDesc(file_mints, 0);

/**
 * @generated from message fractalengine.rpc.v1.GetMintRequest
 */
export type GetMintRequest = Message<"fractalengine.rpc.v1.GetMintRequest"> & {
  /**
   * @generated from field: string hash = 1;
   */
  hash: string;
};

/**
 * Describes the message fractalengine.rpc.v1.GetMintRequest.
 * Use `create(GetMintRequestSchema)` to create a new message.
 */
export const GetMintRequestSchema: GenMessage<GetMintRequest> = /*@__PURE__*/
  messageDesc(file_mints, 1);

/**
 * @generated from message fractalengine.rpc.v1.GetMintsResponse
 */
export type GetMintsResponse = Message<"fractalengine.rpc.v1.GetMintsResponse"> & {
  /**
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * @generated from field: repeated fractalengine.rpc.v1.Mint mints = 2;
   */
  mints: Mint[];

  /**
   * @generated from field: int32 page = 3;
   */
  page: number;

  /**
   * @generated from field: int32 total = 4;
   */
  total: number;
};

/**
 * Describes the message fractalengine.rpc.v1.GetMintsResponse.
 * Use `create(GetMintsResponseSchema)` to create a new message.
 */
export const GetMintsResponseSchema: GenMessage<GetMintsResponse> = /*@__PURE__*/
  messageDesc(file_mints, 2);

/**
 * @generated from message fractalengine.rpc.v1.GetMintResponse
 */
export type GetMintResponse = Message<"fractalengine.rpc.v1.GetMintResponse"> & {
  /**
   * @generated from field: fractalengine.rpc.v1.Mint mint = 1;
   */
  mint?: Mint;
};

/**
 * Describes the message fractalengine.rpc.v1.GetMintResponse.
 * Use `create(GetMintResponseSchema)` to create a new message.
 */
export const GetMintResponseSchema: GenMessage<GetMintResponse> = /*@__PURE__*/
  messageDesc(file_mints, 3);

/**
 * @generated from message fractalengine.rpc.v1.CreateMintRequest
 */
export type CreateMintRequest = Message<"fractalengine.rpc.v1.CreateMintRequest"> & {
  /**
   * @generated from field: fractalengine.rpc.v1.CreateMintRequestPayload payload = 1;
   */
  payload?: CreateMintRequestPayload;

  /**
   * @generated from field: string public_key = 2;
   */
  publicKey: string;

  /**
   * @generated from field: string signature = 3;
   */
  signature: string;
};

/**
 * Describes the message fractalengine.rpc.v1.CreateMintRequest.
 * Use `create(CreateMintRequestSchema)` to create a new message.
 */
export const CreateMintRequestSchema: GenMessage<CreateMintRequest> = /*@__PURE__*/
  messageDesc(file_mints, 4);

/**
 * @generated from message fractalengine.rpc.v1.CreateMintRequestPayload
 */
export type CreateMintRequestPayload = Message<"fractalengine.rpc.v1.CreateMintRequestPayload"> & {
  /**
   * @generated from field: repeated fractalengine.rpc.v1.AssetManager asset_managers = 1;
   */
  assetManagers: AssetManager[];

  /**
   * @generated from field: string contract_of_sale = 2;
   */
  contractOfSale: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: string feed_url = 4;
   */
  feedUrl: string;

  /**
   * @generated from field: int32 fraction_count = 5;
   */
  fractionCount: number;

  /**
   * @generated from field: fractalengine.rpc.v1.StringInterfaceMap lockup_options = 6;
   */
  lockupOptions?: StringInterfaceMap;

  /**
   * @generated from field: fractalengine.rpc.v1.StringInterfaceMap metadata = 7;
   */
  metadata?: StringInterfaceMap;

  /**
   * @generated from field: int32 min_signatures = 8;
   */
  minSignatures: number;

  /**
   * @generated from field: string owner_address = 9;
   */
  ownerAddress: string;

  /**
   * @generated from field: fractalengine.rpc.v1.StringInterfaceMap requirements = 10;
   */
  requirements?: StringInterfaceMap;

  /**
   * @generated from field: fractalengine.rpc.v1.SignatureRequirementType signature_requirement_type = 11;
   */
  signatureRequirementType: SignatureRequirementType;

  /**
   * @generated from field: repeated string tags = 12;
   */
  tags: string[];

  /**
   * @generated from field: string title = 13;
   */
  title: string;
};

/**
 * Describes the message fractalengine.rpc.v1.CreateMintRequestPayload.
 * Use `create(CreateMintRequestPayloadSchema)` to create a new message.
 */
export const CreateMintRequestPayloadSchema: GenMessage<CreateMintRequestPayload> = /*@__PURE__*/
  messageDesc(file_mints, 5);

/**
 * @generated from message fractalengine.rpc.v1.CreateMintResponse
 */
export type CreateMintResponse = Message<"fractalengine.rpc.v1.CreateMintResponse"> & {
  /**
   * @generated from field: string encoded_transaction_body = 1;
   */
  encodedTransactionBody: string;

  /**
   * @generated from field: string hash = 2;
   */
  hash: string;
};

/**
 * Describes the message fractalengine.rpc.v1.CreateMintResponse.
 * Use `create(CreateMintResponseSchema)` to create a new message.
 */
export const CreateMintResponseSchema: GenMessage<CreateMintResponse> = /*@__PURE__*/
  messageDesc(file_mints, 6);

