// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=.js"
// @generated from file mints.proto (package fractalengine.rpc.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb.js";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { AssetManager, Mint, SignatureRequirementType, StringInterfaceMap } from "./common_pb.js";
import { file_common } from "./common_pb.js";
import type { Address, Hash } from "./types_pb.js";
import { file_types } from "./types_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mints.proto.
 */
export const file_mints: GenFile = /*@__PURE__*/
  fileDesc("CgttaW50cy5wcm90bxIUZnJhY3RhbGVuZ2luZS5ycGMudjEiaAoPR2V0TWludHNSZXF1ZXN0EioKBWxpbWl0GAEgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkludDMyVmFsdWUSKQoEcGFnZRgCIAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5JbnQzMlZhbHVlIjoKDkdldE1pbnRSZXF1ZXN0EigKBGhhc2gYASABKAsyGi5mcmFjdGFsZW5naW5lLnJwYy52MS5IYXNoImkKEEdldE1pbnRzUmVzcG9uc2USDQoFbGltaXQYASABKAUSKQoFbWludHMYAiADKAsyGi5mcmFjdGFsZW5naW5lLnJwYy52MS5NaW50EgwKBHBhZ2UYAyABKAUSDQoFdG90YWwYBCABKAUiOwoPR2V0TWludFJlc3BvbnNlEigKBG1pbnQYASABKAsyGi5mcmFjdGFsZW5naW5lLnJwYy52MS5NaW50InsKEUNyZWF0ZU1pbnRSZXF1ZXN0Ej8KB3BheWxvYWQYASABKAsyLi5mcmFjdGFsZW5naW5lLnJwYy52MS5DcmVhdGVNaW50UmVxdWVzdFBheWxvYWQSEgoKcHVibGljX2tleRgCIAEoCRIRCglzaWduYXR1cmUYAyABKAkixwQKGENyZWF0ZU1pbnRSZXF1ZXN0UGF5bG9hZBI6Cg5hc3NldF9tYW5hZ2VycxgBIAMoCzIiLmZyYWN0YWxlbmdpbmUucnBjLnYxLkFzc2V0TWFuYWdlchIYChBjb250cmFjdF9vZl9zYWxlGAIgASgJEhwKC2Rlc2NyaXB0aW9uGAMgASgJQge6SARyAhABEhAKCGZlZWRfdXJsGAQgASgJEh8KDmZyYWN0aW9uX2NvdW50GAUgASgFQge6SAQaAiAAEkAKDmxvY2t1cF9vcHRpb25zGAYgASgLMiguZnJhY3RhbGVuZ2luZS5ycGMudjEuU3RyaW5nSW50ZXJmYWNlTWFwEjoKCG1ldGFkYXRhGAcgASgLMiguZnJhY3RhbGVuZ2luZS5ycGMudjEuU3RyaW5nSW50ZXJmYWNlTWFwEhYKDm1pbl9zaWduYXR1cmVzGAggASgFEjQKDW93bmVyX2FkZHJlc3MYCSABKAsyHS5mcmFjdGFsZW5naW5lLnJwYy52MS5BZGRyZXNzEj4KDHJlcXVpcmVtZW50cxgKIAEoCzIoLmZyYWN0YWxlbmdpbmUucnBjLnYxLlN0cmluZ0ludGVyZmFjZU1hcBJSChpzaWduYXR1cmVfcmVxdWlyZW1lbnRfdHlwZRgLIAEoDjIuLmZyYWN0YWxlbmdpbmUucnBjLnYxLlNpZ25hdHVyZVJlcXVpcmVtZW50VHlwZRIMCgR0YWdzGAwgAygJEhYKBXRpdGxlGA0gASgJQge6SARyAhABImAKEkNyZWF0ZU1pbnRSZXNwb25zZRIgChhlbmNvZGVkX3RyYW5zYWN0aW9uX2JvZHkYASABKAkSKAoEaGFzaBgCIAEoCzIaLmZyYWN0YWxlbmdpbmUucnBjLnYxLkhhc2hCLlosZG9nZWNvaW4ub3JnL2ZyYWN0YWwtZW5naW5lL3BrZy9ycGMvcHJvdG9jb2xiCGVkaXRpb25zcOgH", [file_buf_validate_validate, file_google_protobuf_wrappers, file_common, file_types]);

/**
 * @generated from message fractalengine.rpc.v1.GetMintsRequest
 */
export type GetMintsRequest = Message<"fractalengine.rpc.v1.GetMintsRequest"> & {
  /**
   * @generated from field: google.protobuf.Int32Value limit = 1;
   */
  limit?: number;

  /**
   * @generated from field: google.protobuf.Int32Value page = 2;
   */
  page?: number;
};

/**
 * Describes the message fractalengine.rpc.v1.GetMintsRequest.
 * Use `create(GetMintsRequestSchema)` to create a new message.
 */
export const GetMintsRequestSchema: GenMessage<GetMintsRequest> = /*@__PURE__*/
  messageDesc(file_mints, 0);

/**
 * @generated from message fractalengine.rpc.v1.GetMintRequest
 */
export type GetMintRequest = Message<"fractalengine.rpc.v1.GetMintRequest"> & {
  /**
   * @generated from field: fractalengine.rpc.v1.Hash hash = 1;
   */
  hash?: Hash;
};

/**
 * Describes the message fractalengine.rpc.v1.GetMintRequest.
 * Use `create(GetMintRequestSchema)` to create a new message.
 */
export const GetMintRequestSchema: GenMessage<GetMintRequest> = /*@__PURE__*/
  messageDesc(file_mints, 1);

/**
 * @generated from message fractalengine.rpc.v1.GetMintsResponse
 */
export type GetMintsResponse = Message<"fractalengine.rpc.v1.GetMintsResponse"> & {
  /**
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * @generated from field: repeated fractalengine.rpc.v1.Mint mints = 2;
   */
  mints: Mint[];

  /**
   * @generated from field: int32 page = 3;
   */
  page: number;

  /**
   * @generated from field: int32 total = 4;
   */
  total: number;
};

/**
 * Describes the message fractalengine.rpc.v1.GetMintsResponse.
 * Use `create(GetMintsResponseSchema)` to create a new message.
 */
export const GetMintsResponseSchema: GenMessage<GetMintsResponse> = /*@__PURE__*/
  messageDesc(file_mints, 2);

/**
 * @generated from message fractalengine.rpc.v1.GetMintResponse
 */
export type GetMintResponse = Message<"fractalengine.rpc.v1.GetMintResponse"> & {
  /**
   * @generated from field: fractalengine.rpc.v1.Mint mint = 1;
   */
  mint?: Mint;
};

/**
 * Describes the message fractalengine.rpc.v1.GetMintResponse.
 * Use `create(GetMintResponseSchema)` to create a new message.
 */
export const GetMintResponseSchema: GenMessage<GetMintResponse> = /*@__PURE__*/
  messageDesc(file_mints, 3);

/**
 * @generated from message fractalengine.rpc.v1.CreateMintRequest
 */
export type CreateMintRequest = Message<"fractalengine.rpc.v1.CreateMintRequest"> & {
  /**
   * @generated from field: fractalengine.rpc.v1.CreateMintRequestPayload payload = 1;
   */
  payload?: CreateMintRequestPayload;

  /**
   * @generated from field: string public_key = 2;
   */
  publicKey: string;

  /**
   * @generated from field: string signature = 3;
   */
  signature: string;
};

/**
 * Describes the message fractalengine.rpc.v1.CreateMintRequest.
 * Use `create(CreateMintRequestSchema)` to create a new message.
 */
export const CreateMintRequestSchema: GenMessage<CreateMintRequest> = /*@__PURE__*/
  messageDesc(file_mints, 4);

/**
 * @generated from message fractalengine.rpc.v1.CreateMintRequestPayload
 */
export type CreateMintRequestPayload = Message<"fractalengine.rpc.v1.CreateMintRequestPayload"> & {
  /**
   * @generated from field: repeated fractalengine.rpc.v1.AssetManager asset_managers = 1;
   */
  assetManagers: AssetManager[];

  /**
   * @generated from field: string contract_of_sale = 2;
   */
  contractOfSale: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: string feed_url = 4;
   */
  feedUrl: string;

  /**
   * @generated from field: int32 fraction_count = 5;
   */
  fractionCount: number;

  /**
   * @generated from field: fractalengine.rpc.v1.StringInterfaceMap lockup_options = 6;
   */
  lockupOptions?: StringInterfaceMap;

  /**
   * @generated from field: fractalengine.rpc.v1.StringInterfaceMap metadata = 7;
   */
  metadata?: StringInterfaceMap;

  /**
   * @generated from field: int32 min_signatures = 8;
   */
  minSignatures: number;

  /**
   * @generated from field: fractalengine.rpc.v1.Address owner_address = 9;
   */
  ownerAddress?: Address;

  /**
   * @generated from field: fractalengine.rpc.v1.StringInterfaceMap requirements = 10;
   */
  requirements?: StringInterfaceMap;

  /**
   * @generated from field: fractalengine.rpc.v1.SignatureRequirementType signature_requirement_type = 11;
   */
  signatureRequirementType: SignatureRequirementType;

  /**
   * @generated from field: repeated string tags = 12;
   */
  tags: string[];

  /**
   * @generated from field: string title = 13;
   */
  title: string;
};

/**
 * Describes the message fractalengine.rpc.v1.CreateMintRequestPayload.
 * Use `create(CreateMintRequestPayloadSchema)` to create a new message.
 */
export const CreateMintRequestPayloadSchema: GenMessage<CreateMintRequestPayload> = /*@__PURE__*/
  messageDesc(file_mints, 5);

/**
 * @generated from message fractalengine.rpc.v1.CreateMintResponse
 */
export type CreateMintResponse = Message<"fractalengine.rpc.v1.CreateMintResponse"> & {
  /**
   * @generated from field: string encoded_transaction_body = 1;
   */
  encodedTransactionBody: string;

  /**
   * @generated from field: fractalengine.rpc.v1.Hash hash = 2;
   */
  hash?: Hash;
};

/**
 * Describes the message fractalengine.rpc.v1.CreateMintResponse.
 * Use `create(CreateMintResponseSchema)` to create a new message.
 */
export const CreateMintResponseSchema: GenMessage<CreateMintResponse> = /*@__PURE__*/
  messageDesc(file_mints, 6);

