// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=.js"
// @generated from file payments.proto (package fractalengine.rpc.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb.js";
import type { Hash } from "./types_pb.js";
import { file_types } from "./types_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file payments.proto.
 */
export const file_payments: GenFile = /*@__PURE__*/
  fileDesc("Cg5wYXltZW50cy5wcm90bxIUZnJhY3RhbGVuZ2luZS5ycGMudjEiSwoXQ3JlYXRlTmV3UGF5bWVudFJlcXVlc3QSMAoMaW52b2ljZV9oYXNoGAEgASgLMhouZnJhY3RhbGVuZ2luZS5ycGMudjEuSGFzaCKVAQoYQ3JlYXRlTmV3UGF5bWVudFJlc3BvbnNlEkoKBnZhbHVlcxgBIAMoCzI6LmZyYWN0YWxlbmdpbmUucnBjLnYxLkNyZWF0ZU5ld1BheW1lbnRSZXNwb25zZS5WYWx1ZXNFbnRyeRotCgtWYWx1ZXNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQi5aLGRvZ2Vjb2luLm9yZy9mcmFjdGFsLWVuZ2luZS9wa2cvcnBjL3Byb3RvY29sYghlZGl0aW9uc3DoBw", [file_buf_validate_validate, file_types]);

/**
 * @generated from message fractalengine.rpc.v1.CreateNewPaymentRequest
 */
export type CreateNewPaymentRequest = Message<"fractalengine.rpc.v1.CreateNewPaymentRequest"> & {
  /**
   * @generated from field: fractalengine.rpc.v1.Hash invoice_hash = 1;
   */
  invoiceHash?: Hash | undefined;
};

/**
 * Describes the message fractalengine.rpc.v1.CreateNewPaymentRequest.
 * Use `create(CreateNewPaymentRequestSchema)` to create a new message.
 */
export const CreateNewPaymentRequestSchema: GenMessage<CreateNewPaymentRequest> = /*@__PURE__*/
  messageDesc(file_payments, 0);

/**
 * @generated from message fractalengine.rpc.v1.CreateNewPaymentResponse
 */
export type CreateNewPaymentResponse = Message<"fractalengine.rpc.v1.CreateNewPaymentResponse"> & {
  /**
   * @generated from field: map<string, string> values = 1;
   */
  values: { [key: string]: string };
};

/**
 * Describes the message fractalengine.rpc.v1.CreateNewPaymentResponse.
 * Use `create(CreateNewPaymentResponseSchema)` to create a new message.
 */
export const CreateNewPaymentResponseSchema: GenMessage<CreateNewPaymentResponse> = /*@__PURE__*/
  messageDesc(file_payments, 1);

