// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=.js"
// @generated from file payments.proto (package fractalengine.rpc.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file payments.proto.
 */
export const file_payments: GenFile = /*@__PURE__*/
  fileDesc("Cg5wYXltZW50cy5wcm90bxIUZnJhY3RhbGVuZ2luZS5ycGMudjEiSQoXQ3JlYXRlTmV3UGF5bWVudFJlcXVlc3QSLgoMaW52b2ljZV9oYXNoGAEgASgJQhi6SBVyEzIRXlthLWZBLUYwLTldezY0fSQilQEKGENyZWF0ZU5ld1BheW1lbnRSZXNwb25zZRJKCgZ2YWx1ZXMYASADKAsyOi5mcmFjdGFsZW5naW5lLnJwYy52MS5DcmVhdGVOZXdQYXltZW50UmVzcG9uc2UuVmFsdWVzRW50cnkaLQoLVmFsdWVzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AUIuWixkb2dlY29pbi5vcmcvZnJhY3RhbC1lbmdpbmUvcGtnL3JwYy9wcm90b2NvbGIGcHJvdG8z", [file_buf_validate_validate]);

/**
 * @generated from message fractalengine.rpc.v1.CreateNewPaymentRequest
 */
export type CreateNewPaymentRequest = Message<"fractalengine.rpc.v1.CreateNewPaymentRequest"> & {
  /**
   * @generated from field: string invoice_hash = 1;
   */
  invoiceHash: string;
};

/**
 * Describes the message fractalengine.rpc.v1.CreateNewPaymentRequest.
 * Use `create(CreateNewPaymentRequestSchema)` to create a new message.
 */
export const CreateNewPaymentRequestSchema: GenMessage<CreateNewPaymentRequest> = /*@__PURE__*/
  messageDesc(file_payments, 0);

/**
 * @generated from message fractalengine.rpc.v1.CreateNewPaymentResponse
 */
export type CreateNewPaymentResponse = Message<"fractalengine.rpc.v1.CreateNewPaymentResponse"> & {
  /**
   * @generated from field: map<string, string> values = 1;
   */
  values: { [key: string]: string };
};

/**
 * Describes the message fractalengine.rpc.v1.CreateNewPaymentResponse.
 * Use `create(CreateNewPaymentResponseSchema)` to create a new message.
 */
export const CreateNewPaymentResponseSchema: GenMessage<CreateNewPaymentResponse> = /*@__PURE__*/
  messageDesc(file_payments, 1);

