// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=.js"
// @generated from file stats.proto (package fractalengine.rpc.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file stats.proto.
 */
export const file_stats: GenFile = /*@__PURE__*/
  fileDesc("CgtzdGF0cy5wcm90bxIUZnJhY3RhbGVuZ2luZS5ycGMudjEiggEKEEdldFN0YXRzUmVzcG9uc2USQAoFc3RhdHMYASADKAsyMS5mcmFjdGFsZW5naW5lLnJwYy52MS5HZXRTdGF0c1Jlc3BvbnNlLlN0YXRzRW50cnkaLAoKU3RhdHNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAU6AjgBIhEKD0dldFN0YXRzUmVxdWVzdEIuWixkb2dlY29pbi5vcmcvZnJhY3RhbC1lbmdpbmUvcGtnL3JwYy9wcm90b2NvbGIGcHJvdG8z");

/**
 * @generated from message fractalengine.rpc.v1.GetStatsResponse
 */
export type GetStatsResponse = Message<"fractalengine.rpc.v1.GetStatsResponse"> & {
  /**
   * @generated from field: map<string, int32> stats = 1;
   */
  stats: { [key: string]: number };
};

/**
 * Describes the message fractalengine.rpc.v1.GetStatsResponse.
 * Use `create(GetStatsResponseSchema)` to create a new message.
 */
export const GetStatsResponseSchema: GenMessage<GetStatsResponse> = /*@__PURE__*/
  messageDesc(file_stats, 0);

/**
 * @generated from message fractalengine.rpc.v1.GetStatsRequest
 */
export type GetStatsRequest = Message<"fractalengine.rpc.v1.GetStatsRequest"> & {
};

/**
 * Describes the message fractalengine.rpc.v1.GetStatsRequest.
 * Use `create(GetStatsRequestSchema)` to create a new message.
 */
export const GetStatsRequestSchema: GenMessage<GetStatsRequest> = /*@__PURE__*/
  messageDesc(file_stats, 1);

