// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=.js"
// @generated from file tokens.proto (package fractalengine.rpc.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb.js";
import { file_google_protobuf_struct, file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { TokenBalance } from "./common_pb.js";
import { file_common } from "./common_pb.js";
import type { Address, Hash } from "./types_pb.js";
import { file_types } from "./types_pb.js";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file tokens.proto.
 */
export const file_tokens: GenFile = /*@__PURE__*/
  fileDesc("Cgx0b2tlbnMucHJvdG8SFGZyYWN0YWxlbmdpbmUucnBjLnYxIn8KHkdldFBlbmRpbmdUb2tlbkJhbGFuY2VzUmVxdWVzdBIuCgdhZGRyZXNzGAEgASgLMh0uZnJhY3RhbGVuZ2luZS5ycGMudjEuQWRkcmVzcxItCgltaW50X2hhc2gYAiABKAsyGi5mcmFjdGFsZW5naW5lLnJwYy52MS5IYXNoIlcKH0dldFBlbmRpbmdUb2tlbkJhbGFuY2VzUmVzcG9uc2USNAoIYmFsYW5jZXMYASADKAsyIi5mcmFjdGFsZW5naW5lLnJwYy52MS5Ub2tlbkJhbGFuY2UiiQIKF0dldFRva2VuQmFsYW5jZXNSZXF1ZXN0Ei4KB2FkZHJlc3MYASABKAsyHS5mcmFjdGFsZW5naW5lLnJwYy52MS5BZGRyZXNzEi0KCW1pbnRfaGFzaBgCIAEoCzIaLmZyYWN0YWxlbmdpbmUucnBjLnYxLkhhc2gSOAoUaW5jbHVkZV9taW50X2RldGFpbHMYAyABKAsyGi5nb29nbGUucHJvdG9idWYuQm9vbFZhbHVlEioKBWxpbWl0GAQgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkludDMyVmFsdWUSKQoEcGFnZRgFIAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5JbnQzMlZhbHVlIkEKGEdldFRva2VuQmFsYW5jZXNSZXNwb25zZRIlCgRkYXRhGAEgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdEIuWixkb2dlY29pbi5vcmcvZnJhY3RhbC1lbmdpbmUvcGtnL3JwYy9wcm90b2NvbGIIZWRpdGlvbnNw6Ac", [file_buf_validate_validate, file_google_protobuf_struct, file_google_protobuf_wrappers, file_common, file_types]);

/**
 * @generated from message fractalengine.rpc.v1.GetPendingTokenBalancesRequest
 */
export type GetPendingTokenBalancesRequest = Message<"fractalengine.rpc.v1.GetPendingTokenBalancesRequest"> & {
  /**
   * @generated from field: fractalengine.rpc.v1.Address address = 1;
   */
  address?: Address | undefined;

  /**
   * @generated from field: fractalengine.rpc.v1.Hash mint_hash = 2;
   */
  mintHash?: Hash | undefined;
};

/**
 * Describes the message fractalengine.rpc.v1.GetPendingTokenBalancesRequest.
 * Use `create(GetPendingTokenBalancesRequestSchema)` to create a new message.
 */
export const GetPendingTokenBalancesRequestSchema: GenMessage<GetPendingTokenBalancesRequest> = /*@__PURE__*/
  messageDesc(file_tokens, 0);

/**
 * @generated from message fractalengine.rpc.v1.GetPendingTokenBalancesResponse
 */
export type GetPendingTokenBalancesResponse = Message<"fractalengine.rpc.v1.GetPendingTokenBalancesResponse"> & {
  /**
   * @generated from field: repeated fractalengine.rpc.v1.TokenBalance balances = 1;
   */
  balances: TokenBalance[];
};

/**
 * Describes the message fractalengine.rpc.v1.GetPendingTokenBalancesResponse.
 * Use `create(GetPendingTokenBalancesResponseSchema)` to create a new message.
 */
export const GetPendingTokenBalancesResponseSchema: GenMessage<GetPendingTokenBalancesResponse> = /*@__PURE__*/
  messageDesc(file_tokens, 1);

/**
 * @generated from message fractalengine.rpc.v1.GetTokenBalancesRequest
 */
export type GetTokenBalancesRequest = Message<"fractalengine.rpc.v1.GetTokenBalancesRequest"> & {
  /**
   * @generated from field: fractalengine.rpc.v1.Address address = 1;
   */
  address?: Address | undefined;

  /**
   * @generated from field: fractalengine.rpc.v1.Hash mint_hash = 2;
   */
  mintHash?: Hash | undefined;

  /**
   * @generated from field: google.protobuf.BoolValue include_mint_details = 3;
   */
  includeMintDetails?: boolean | undefined;

  /**
   * @generated from field: google.protobuf.Int32Value limit = 4;
   */
  limit?: number | undefined;

  /**
   * @generated from field: google.protobuf.Int32Value page = 5;
   */
  page?: number | undefined;
};

/**
 * Describes the message fractalengine.rpc.v1.GetTokenBalancesRequest.
 * Use `create(GetTokenBalancesRequestSchema)` to create a new message.
 */
export const GetTokenBalancesRequestSchema: GenMessage<GetTokenBalancesRequest> = /*@__PURE__*/
  messageDesc(file_tokens, 2);

/**
 * @generated from message fractalengine.rpc.v1.GetTokenBalancesResponse
 */
export type GetTokenBalancesResponse = Message<"fractalengine.rpc.v1.GetTokenBalancesResponse"> & {
  /**
   * @generated from field: google.protobuf.Struct data = 1;
   */
  data?: JsonObject | undefined;
};

/**
 * Describes the message fractalengine.rpc.v1.GetTokenBalancesResponse.
 * Use `create(GetTokenBalancesResponseSchema)` to create a new message.
 */
export const GetTokenBalancesResponseSchema: GenMessage<GetTokenBalancesResponse> = /*@__PURE__*/
  messageDesc(file_tokens, 3);

