// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=.js"
// @generated from file tokens.proto (package fractalengine.rpc.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb.js";
import { file_google_protobuf_struct, file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { TokenBalance } from "./common_pb.js";
import { file_common } from "./common_pb.js";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file tokens.proto.
 */
export const file_tokens: GenFile = /*@__PURE__*/
  fileDesc("Cgx0b2tlbnMucHJvdG8SFGZyYWN0YWxlbmdpbmUucnBjLnYxIq0BCh5HZXRQZW5kaW5nVG9rZW5CYWxhbmNlc1JlcXVlc3QSQAoHYWRkcmVzcxgBIAEoCUIvukgscioyKF4oPzpbREFtbjJdKVsxLTlBLUhKLU5QLVphLWttLXpdezI1LDM0fSQSSQoJbWludF9oYXNoGAIgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlQhi6SBVyEzIRXlthLWZBLUYwLTldezY0fSQiVwofR2V0UGVuZGluZ1Rva2VuQmFsYW5jZXNSZXNwb25zZRI0CghiYWxhbmNlcxgBIAMoCzIiLmZyYWN0YWxlbmdpbmUucnBjLnYxLlRva2VuQmFsYW5jZSK3AgoXR2V0VG9rZW5CYWxhbmNlc1JlcXVlc3QSQAoHYWRkcmVzcxgBIAEoCUIvukgscioyKF4oPzpbREFtbjJdKVsxLTlBLUhKLU5QLVphLWttLXpdezI1LDM0fSQSSQoJbWludF9oYXNoGAIgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlQhi6SBVyEzIRXlthLWZBLUYwLTldezY0fSQSOAoUaW5jbHVkZV9taW50X2RldGFpbHMYAyABKAsyGi5nb29nbGUucHJvdG9idWYuQm9vbFZhbHVlEioKBWxpbWl0GAQgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkludDMyVmFsdWUSKQoEcGFnZRgFIAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5JbnQzMlZhbHVlIkEKGEdldFRva2VuQmFsYW5jZXNSZXNwb25zZRIlCgRkYXRhGAEgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdEIuWixkb2dlY29pbi5vcmcvZnJhY3RhbC1lbmdpbmUvcGtnL3JwYy9wcm90b2NvbGIGcHJvdG8z", [file_buf_validate_validate, file_google_protobuf_struct, file_google_protobuf_wrappers, file_common]);

/**
 * @generated from message fractalengine.rpc.v1.GetPendingTokenBalancesRequest
 */
export type GetPendingTokenBalancesRequest = Message<"fractalengine.rpc.v1.GetPendingTokenBalancesRequest"> & {
  /**
   * @generated from field: string address = 1;
   */
  address: string;

  /**
   * @generated from field: google.protobuf.StringValue mint_hash = 2;
   */
  mintHash?: string;
};

/**
 * Describes the message fractalengine.rpc.v1.GetPendingTokenBalancesRequest.
 * Use `create(GetPendingTokenBalancesRequestSchema)` to create a new message.
 */
export const GetPendingTokenBalancesRequestSchema: GenMessage<GetPendingTokenBalancesRequest> = /*@__PURE__*/
  messageDesc(file_tokens, 0);

/**
 * @generated from message fractalengine.rpc.v1.GetPendingTokenBalancesResponse
 */
export type GetPendingTokenBalancesResponse = Message<"fractalengine.rpc.v1.GetPendingTokenBalancesResponse"> & {
  /**
   * @generated from field: repeated fractalengine.rpc.v1.TokenBalance balances = 1;
   */
  balances: TokenBalance[];
};

/**
 * Describes the message fractalengine.rpc.v1.GetPendingTokenBalancesResponse.
 * Use `create(GetPendingTokenBalancesResponseSchema)` to create a new message.
 */
export const GetPendingTokenBalancesResponseSchema: GenMessage<GetPendingTokenBalancesResponse> = /*@__PURE__*/
  messageDesc(file_tokens, 1);

/**
 * @generated from message fractalengine.rpc.v1.GetTokenBalancesRequest
 */
export type GetTokenBalancesRequest = Message<"fractalengine.rpc.v1.GetTokenBalancesRequest"> & {
  /**
   * @generated from field: string address = 1;
   */
  address: string;

  /**
   * @generated from field: google.protobuf.StringValue mint_hash = 2;
   */
  mintHash?: string;

  /**
   * @generated from field: google.protobuf.BoolValue include_mint_details = 3;
   */
  includeMintDetails?: boolean;

  /**
   * @generated from field: google.protobuf.Int32Value limit = 4;
   */
  limit?: number;

  /**
   * @generated from field: google.protobuf.Int32Value page = 5;
   */
  page?: number;
};

/**
 * Describes the message fractalengine.rpc.v1.GetTokenBalancesRequest.
 * Use `create(GetTokenBalancesRequestSchema)` to create a new message.
 */
export const GetTokenBalancesRequestSchema: GenMessage<GetTokenBalancesRequest> = /*@__PURE__*/
  messageDesc(file_tokens, 2);

/**
 * @generated from message fractalengine.rpc.v1.GetTokenBalancesResponse
 */
export type GetTokenBalancesResponse = Message<"fractalengine.rpc.v1.GetTokenBalancesResponse"> & {
  /**
   * @generated from field: google.protobuf.Struct data = 1;
   */
  data?: JsonObject;
};

/**
 * Describes the message fractalengine.rpc.v1.GetTokenBalancesResponse.
 * Use `create(GetTokenBalancesResponseSchema)` to create a new message.
 */
export const GetTokenBalancesResponseSchema: GenMessage<GetTokenBalancesResponse> = /*@__PURE__*/
  messageDesc(file_tokens, 3);

