// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=.js"
// @generated from file types.proto (package fractalengine.rpc.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types.proto.
 */
export const file_types: GenFile = /*@__PURE__*/
  fileDesc("Cgt0eXBlcy5wcm90bxIUZnJhY3RhbGVuZ2luZS5ycGMudjEiLwoESGFzaBInCgV2YWx1ZRgBIAEoCUIYukgVchMyEV5bYS1mQS1GMC05XXs2NH0kIkgKB0FkZHJlc3MSPQoFdmFsdWUYASABKAlCLrpIK3IpMicoPzpbREFtbjJdKVsxLTlBLUhKLU5QLVphLWttLXpdezI1LDM0fSRCLlosZG9nZWNvaW4ub3JnL2ZyYWN0YWwtZW5naW5lL3BrZy9ycGMvcHJvdG9jb2xiCGVkaXRpb25zcOgH", [file_buf_validate_validate]);

/**
 * @generated from message fractalengine.rpc.v1.Hash
 */
export type Hash = Message<"fractalengine.rpc.v1.Hash"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message fractalengine.rpc.v1.Hash.
 * Use `create(HashSchema)` to create a new message.
 */
export const HashSchema: GenMessage<Hash> = /*@__PURE__*/
  messageDesc(file_types, 0);

/**
 * @generated from message fractalengine.rpc.v1.Address
 */
export type Address = Message<"fractalengine.rpc.v1.Address"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message fractalengine.rpc.v1.Address.
 * Use `create(AddressSchema)` to create a new message.
 */
export const AddressSchema: GenMessage<Address> = /*@__PURE__*/
  messageDesc(file_types, 1);

